フロントエンドの諸々整備
bookbok/bookbok pull request #8
Opened 2021-07-03 14:40 UTC by kento-oka

2021-07-04 14:23 UTC, NAKKA-K approved these changes

2021-07-04 14:26 UTC, NAKKA-K commented on front/.eslintrc
> +    "@typescript-eslint/explicit-module-boundary-types": "off",
これないのちょっと怖いけどな。
FunctionComponentも基本的には変数事態に型付けるパターンが多いからこれに引っかかるってなると面倒なのは確か。

2021-07-04 14:28 UTC, NAKKA-K requested changes
全部見る前にapproveミスって押した

2021-07-04 14:59 UTC, NAKKA-K commented on front/app/page/index.tsx
> +export function Page() {
複数のページをまとめてRouterとかいろいろ良い感じにしてるやつってことだよね。
page/とpages/があるの分かりづらいし命名を考えたい。
安易に考えるならRootPageとか？

2021-07-04 15:30 UTC, NAKKA-K commented on front/app/page/index.tsx
> +export function Page() {
複数のページをまとめてRouterとかいろいろ良い感じにしてるやつってことだよね。
page/とpages/があるの分かりづらいし命名を考えたい。
安易に考えるならRootPageとか？

2021-07-04 15:30 UTC, NAKKA-K commented on front/app/pages/about/index.tsx
> +    </div>
今回のPRで作ったページが今後の参考になるならここも別コンポーネントに分けるといいかも。
front/app/pages/about/About.tsxとかにしてUI部分とdispatchの組み込みとかを切り分けた方がページの見通しがしやすい。

2021-07-04 15:30 UTC, NAKKA-K commented on front/app/pages/types.ts
> +}
このpageTypeはどう言う意図だろう？

後、ページごとに使う型はfront/app/pages/about/types.tsxに書くと見通しが良い。
pagesのルートに書くtypesは可能な限り少なくしたい。
pageTypeとかの意図にもよりそうだけど。

2021-07-04 15:30 UTC, NAKKA-K commented on front/webpack.base.js
> +const path = require('path');
どちらでも大丈夫だけどimportにできないんだっけ？

2021-07-22 08:50 UTC, kento-oka commented on front/webpack.base.js
> +const path = require('path');
webpack.config.jsはcjsで書かれていないと実行できないのでは？

tscとかを挟んでかけるかもしれないけど、そこまで複雑なものでもないしという気持ち

2021-07-22 11:57 UTC, kento-oka commented
https://github.com/bookbok/bookbok/pull/9　に移動

2021-07-22 11:57 UTC, closed without merging

2021-07-22 12:02 UTC, kento-oka commented on front/app/pages/types.ts
> +}
https://github.com/bookbok/bookbok/pull/9 で消えた

2021-07-22 12:02 UTC, kento-oka commented on front/app/page/index.tsx
> +export function Page() {
https://github.com/bookbok/bookbok/pull/9 で場所が変わって名前とかも変わっている

2021-07-22 12:03 UTC, kento-oka commented on front/app/pages/about/index.tsx
> +    </div>
コンポーネントの中身にもよるし、実装時に勝手にやってくれという感じ。

aboutみたいに動きが必要ないコンポーネントを並べるだけのページなら多段にする必要もないし。